/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion_sql.conexion_sql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class sistema extends javax.swing.JFrame {

    //instanciamos la conexion 
    
    conexion_sql cc = new conexion_sql();
    Connection con = cc.conexion();
    
    
    
    public sistema() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        Materia = new javax.swing.JLabel();
        Calificacion = new javax.swing.JLabel();
        txtCalificacion = new javax.swing.JTextField();
        comboMateria = new javax.swing.JComboBox<>();
        botonNuevo = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        busqueda = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        nombre.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        apellidos.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        apellidos.setForeground(new java.awt.Color(255, 255, 255));
        apellidos.setText("Apellidos");

        txtApellidos.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        Materia.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        Materia.setForeground(new java.awt.Color(255, 255, 255));
        Materia.setText("Materia");

        Calificacion.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        Calificacion.setForeground(new java.awt.Color(255, 255, 255));
        Calificacion.setText("Calificación");

        txtCalificacion.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N

        comboMateria.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        comboMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programación ", "Álgebra", "Inglés", "Circuitos", "Física", "Acústica", " " }));
        comboMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMateriaActionPerformed(evt);
            }
        });

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        icono.setIcon(new javax.swing.ImageIcon("C:\\Users\\aula1\\Desktop\\E4\\ulpgc.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icono)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(apellidos)
                                .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Calificacion))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Materia)
                    .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonGuardar)
                    .addComponent(botonEliminar)
                    .addComponent(botonActualizar))
                .addGap(80, 80, 80))
        );

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAlumnos);

        busqueda.setText("Busqueda:");

        txtBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaMouseClicked(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busqueda)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busqueda)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void comboMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMateriaActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        actualizarDatos();
        limpiarElementos();
        mostrarDatos();
        
        
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        insertarDatos();
        limpiarElementos();
        mostrarDatos();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void tablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnosMouseClicked
        
        int filaSeleccionada = tablaAlumnos.rowAtPoint(evt.getPoint());
        
        txtNombre.setText(tablaAlumnos.getValueAt(filaSeleccionada, 1).toString());
        txtApellidos.setText(tablaAlumnos.getValueAt(filaSeleccionada, 2).toString());
        comboMateria.setSelectedItem(tablaAlumnos.getValueAt(filaSeleccionada, 3));
        txtCalificacion.setText(tablaAlumnos.getValueAt(filaSeleccionada, 4).toString());
        
    }//GEN-LAST:event_tablaAlumnosMouseClicked

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        eliminarRegistro();
        mostrarDatos();
        limpiarElementos();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void txtBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaMouseClicked

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
       buscarRegistro(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyReleased
    
    public void mostrarDatos(){
        String [] titulos = { "ID ", "Nombre ", "Apellidos", "Materia ", "Calificacion "};
        String [] registros = new String [7];
        
        DefaultTableModel modelo = new DefaultTableModel (null , titulos);
        
        // sirve para consultar la base de datos de alumnos
        String SQL = "select * from alumnos";
        
        try{
            
            Statement st = con.createStatement ();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){
                
                registros [0] = rs.getString("idalumnos");
                registros [1] = rs.getString("nombre");
                registros [2] = rs.getString("apellidos");
                registros [3] = rs.getString("materia");
                registros [4] = rs.getString("calificacion");
                
                modelo.addRow(registros);
                
            }
            
            tablaAlumnos.setModel(modelo);
        }catch (Exception e){
            
            JOptionPane.showMessageDialog(null, "Error al mostar los datos" + e.getMessage());
            
        }
        
    }
    
        public void actualizarDatos(){
            
        try{
            String SQL = " update alumnos set nombre =?, apellidos=? , materia=? , calificacion=?  where idalumnos = ?";
            
            int filaSeleccionada = tablaAlumnos.getSelectedRow();
            String dao = (String)tablaAlumnos.getValueAt(filaSeleccionada, 0);
            PreparedStatement pst = con.prepareStatement (SQL);
            
            // Hacemos referencia a la columna numero 1 y el campo que queremos introducir. 
            pst.setString(1, txtNombre.getText());
            
            pst.setString(2, txtApellidos.getText());
            
            // Para tratar el como box, declaramos primero la variable entera
            
            int seleccionado = comboMateria.getSelectedIndex();
            pst.setString(3, comboMateria.getItemAt(seleccionado));
           
            pst.setDouble(4, Double.parseDouble(txtCalificacion.getText()));
            
            // Ejecutamos la consulta
            
            
            pst.setString(5, dao);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Registro actualizado");
            
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al actualizar " + e.getMessage());
            
        }
    }
        
    
    
    
    public void insertarDatos (){
        try{
            String SQL = "insert into alumnos (nombre, apellidos, materia, calificacion)values ( ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement (SQL);
            
            // Hacemos referencia a la columna numero 1 y el campo que queremos introducir. 
            pst.setString(1, txtNombre.getText());
            
            pst.setString(2, txtApellidos.getText());
            
            // Para tratar el como box, declaramos primero la variable entera
            
            int seleccionado = comboMateria.getSelectedIndex();
            pst.setString(3, comboMateria.getItemAt(seleccionado));
           
            pst.setDouble(4, Double.parseDouble(txtCalificacion.getText()));
            
            // Ejecutamos la consulta
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Registro realizado");
            
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error en el registro " + e.getMessage());
            
        }
    }
    
    public void eliminarRegistro(){
        
        int filaSeleccioanda = tablaAlumnos.getSelectedRow();
        
        try{
            String SQL = "delete from alumnos where idalumnos = " + tablaAlumnos.getValueAt(filaSeleccioanda, 0);
            
            Statement st= con.createStatement();
            
            int n = st.executeUpdate(SQL);
            
            if (n>=0){
                JOptionPane.showConfirmDialog( null, "Registro Eliminado");
            }
            
        }catch (Exception e){
            JOptionPane.showConfirmDialog( null, "Error al elimianrlo" + e.getMessage());
        }
        
    }
    
    public void buscarRegistro(String valor){
        
            String [] titulos = { "ID ", "Nombre ", "Apellidos", "Materia ", "Calificacion "};
        String [] registros = new String [7];
        
        DefaultTableModel modelo = new DefaultTableModel (null , titulos);
        
        // sirve para consultar la base de datos de alumnos
        String SQL = "select * from alumnos where nombre like '%" + valor + "%'";
        
        try{
            
            Statement st = con.createStatement ();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){
                
                registros [0] = rs.getString("idalumnos");
                registros [1] = rs.getString("nombre");
                registros [2] = rs.getString("apellidos");
                registros [3] = rs.getString("materia");
                registros [4] = rs.getString("calificacion");
                
                modelo.addRow(registros);
                
            }
            
            tablaAlumnos.setModel(modelo);
        }catch (Exception e){
            
            JOptionPane.showMessageDialog(null, "Error al mostar los datos" + e.getMessage());
            
        }
        
    
    }
    
    public void limpiarElementos(){
        
        txtNombre.setText("");
        txtApellidos.setText("");
        txtCalificacion.setText("");
        comboMateria.setSelectedItem(null);
    }
    
    public void eliminarAlumno(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calificacion;
    private javax.swing.JLabel Materia;
    private javax.swing.JLabel apellidos;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JLabel busqueda;
    private javax.swing.JComboBox<String> comboMateria;
    private javax.swing.JLabel icono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
